services:
  web:
    build: .
    command: python -m flask --app 'backend' run --host=0.0.0.0
    ports:
      - "5000:5000"
    develop:
      watch:
        - action: sync
          path: .
          target: /code
  anirecsmongo:
    image: "mongo:8.0.1"